### ISSUE TITLE
tried to upload to my new feather board and i get errors

### ISSUE THREAD

**Issue by mpkottawa** [ridercz/PrusaCam#1]
the start, it says 
#include <Arduino.h>
#include <SPI.h>
#include "Adafruit_BLE.h"
#include "Adafruit_BluefruitLE_SPI.h"
#include "PrusaCamConfig.h"

the only file it has is PrusaCamConfig.h.    i get Adafruit_BLE.h: No such file or directory

**Comment by ridercz** [comment]
You don't have the `Adafruit BLEFirmata` library installed. Follow instructions available [here](https://blog.prusaprinters.org/how-to-make-3d-print-time-lapses-with-your-smartphone-camera/).

**Comment by mpkottawa** [comment]
ok, i had that library downloaded but i didnt actually click it to include
it.   now, im getting:

 Adafruit_BLE.h:42:35: error: utility/common_header.h: No such file or
directory, in the adafruit_ble.h tab.
